apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xbnt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-xbnt@sha256:1aae159a96ab731a0eb3ff1c20cf70ac1df55271c22bdcec17a2e3595cc3d124
        name: my-nodejs
        resources: {}
status: {}
